// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzs6In9SpwBumpvkjHAq0PGJf79GrMkqU',
    appId: '1:115932544823:web:c630730abd6031a5d4e4b2',
    messagingSenderId: '115932544823',
    projectId: 'ailoitte-58051',
    authDomain: 'ailoitte-58051.firebaseapp.com',
    storageBucket: 'ailoitte-58051.firebasestorage.app',
    measurementId: 'G-C8YHVJ2YG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr0Rw1e33-O68e0Meo5NQ34HLR4W_9XDY',
    appId: '1:115932544823:android:a9fe2cd333e23aa7d4e4b2',
    messagingSenderId: '115932544823',
    projectId: 'ailoitte-58051',
    storageBucket: 'ailoitte-58051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcgJuKEgKoydsxNcI0H1SH0wN4Fmi_ndw',
    appId: '1:115932544823:ios:bd1ab929151de4abd4e4b2',
    messagingSenderId: '115932544823',
    projectId: 'ailoitte-58051',
    storageBucket: 'ailoitte-58051.firebasestorage.app',
    iosBundleId: 'com.ailoitte.ailoitte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcgJuKEgKoydsxNcI0H1SH0wN4Fmi_ndw',
    appId: '1:115932544823:ios:bd1ab929151de4abd4e4b2',
    messagingSenderId: '115932544823',
    projectId: 'ailoitte-58051',
    storageBucket: 'ailoitte-58051.firebasestorage.app',
    iosBundleId: 'com.ailoitte.ailoitte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzs6In9SpwBumpvkjHAq0PGJf79GrMkqU',
    appId: '1:115932544823:web:a529b0ed4f07dd7bd4e4b2',
    messagingSenderId: '115932544823',
    projectId: 'ailoitte-58051',
    authDomain: 'ailoitte-58051.firebaseapp.com',
    storageBucket: 'ailoitte-58051.firebasestorage.app',
    measurementId: 'G-P7XE1J4DE4',
  );
}
